import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import {GraphQLClient, gql} from 'graphql-request';
import { useEffect, useState } from 'react';
import BlogCard from "../components/BlogCard";

const graphcms = new GraphQLClient('https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clbwje89o0ilx01t1aqfo8gi6/master');
const QUERY = gql`
{
  posts{
    id,
    title,
    datePublished,
    slug,
    content{
      html
    }
    author{
      name,
      avatar,
      {
        url
      }
    }
    coverPhoto{
        url
    }
  }
}`;

export async function getStaticProps()
{
  const { posts } = await graphcms.request(QUERY);
  return{
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>BLOG</h1>
      {posts.map((post) => (
        <BlogCard title={post.title} author={post.author} coverPhoto={post.coverPhoto} key={post.id} datePublished={post.datePublished} slug={post.slug}/>
      ))}
      </main>
    </>
  )
}
